server:
  port: 80
spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.82.236:1111

#定义服务提供者的微服务名称
service-url:
  nacos-payment-service-url: http://nacos-payment-provider
