server:
  port: 9001

spring:
  application:
    name: gateway-gateway-9001
  cloud:
    gateway:
      #开启动态路由，根据服务名调用
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_get #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://provider-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            #- After=2020-06-21T18:25:10.016+08:00[Asia/Shanghai]
            #- Before=2020-06-28T18:25:10.016+08:00[Asia/Shanghai]
            #- Between=2020-06-21T18:25:10.016+08:00[Asia/Shanghai],2020-06-28T18:25:10.016+08:00[Asia/Shanghai]
        - id: payment_lb
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://provider-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}


