server:
  port: 80
spring:
  application:
    name: cloud-sentinel-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.82.236:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
service:
  url:
    paymentUrl: http://cloud-sentinel-payment-provider
feign:
  sentinel:
    enabled: true
